### ISSUE TITLE
Swimming Person

### ISSUE THREAD

**Issue by yaoshanliang** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#4]
I have a question that in the object_type_dict there is a type called swimming person.
 However, in the XML file, there is no type of swimming person.

**Comment by tilemmpon** [comment]
The "object_type_dict" in the Notebooks includes all the labels given by the authors of the SMD (see https://drive.google.com/file/d/0B10RxHxW3I92NjRjZnN1bjVjelk/view). The label "swimming person" was given by the authors however there is no instance of a swimming person annotated in the dataset. Thus, the generated labels (XML/CSV) will not have such an instance since it does not exist.
