### ISSUE TITLE
What is the difference between first and second data here?

### ISSUE THREAD

**Issue by ingbeeedd** [tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#9]
Hello! 
Is there a history of first and second dataset when I first encounter SMD data? 
I wonder what the difference is.
Is it okay to proceed with the second now?
Thank you

**Comment by ingbeeedd** [comment]
As a result, about 230 frame data have more frame data in the second dataset!

**Comment by ingbeeedd** [comment]
Is it just the difference in the percentage?

**Comment by ingbeeedd** [comment]
Isn't it necessary to divide it into a group split for accurate train and valid? 
I think network can find it quickly if cut it in front and back of the same video frame, but didn't you have any of the following symptoms in the actual test?

**Comment by tilemmpon** [comment]
Hi ingbeeedd,

Thank you for your interest in my repository. As I explain [here](https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics#explanation-of-jupyter-notebooks) for the first dataset I split every video's frame into train/test datasets with ration 0.7/0.3. For the second dataset generation I wanted to see how it the DL models will work if I left some videos completely in the test dataset; thus for the second dataset some videos are fully in test dataset and the rest are split with same ratio (0.7/0.3) into train/test datasets.

**Comment by ingbeeedd** [comment]
Thank you for your answer.
Was there a big gap between val_map and test_map when you tested the second data set?

**Comment by tilemmpon** [comment]
Could you define what you mean by "val_map" and "test_map"? 

If I understand correctly your question, I only split the dataset into 2 parts train and test (or train and validation if you prefer) where I trained on the train dataset and when complete tested on the test dataset, Since I did not create/use validation dataset thus I haven't/couldn't calculated the comparison result difference you asked.

**Comment by ingbeeedd** [comment]
val_map means valid mAP, test_map means test mAP

I told you that if you divide the train/test in the same video, it will not be able to verify the performance correctly!

**Comment by tilemmpon** [comment]
I now understand what you meant. Due to the limited size of this dataset I made the choice of actually splitting every video into train and test data. If you check the data analysis, there are some objects that appear only in some videos thus in order to include learning them I made this choice. Moreover, when selecting which videos to include completely as test data in the second dataset I have chosen videos that include objects with many instances dataset-wise. Indeed had we more data it would be better to split the videos into train/test and not the frames of the videos.

In any case, you can always adapt my notebooks/code in this repository and split the videos/frames as you consider better.
